# fly.toml file generated for 21-online-backend on 2023-03-09T20:46:10+01:00

app = "21-online-backend"
kill_signal = "SIGINT"
kill_timeout = 5
primary_region = "waw"
processes = []

[env]
  PORT = "2567"
  NODE_ENV = "production"

[experimental]
  auto_rollback = true

[[services]]
  http_checks = []
  internal_port = 2567
  processes = ["app"]
  protocol = "tcp"
  script_checks = []
  [services.concurrency]
    hard_limit = 100000
    soft_limit = 100000
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"
